import { collection,getDocs,doc,setDoc } from "firebase/firestore";
import { auth,db } from "./firebase";

const isAdmin=()=>localStorage.getItem('sfd_perfil_acesso')==='admin'&&localStorage.getItem('sfd_admin_autorizado')==='1';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function acessos(){const s=await getDocs(collection(db,'documentos'));return s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.tipo==='acesso_professor').sort((a,b)=>String(b.solicitadoEm||'').localeCompare(String(a.solicitadoEm||'')));}
async function mudar(x,status,obs=''){await setDoc(doc(db,'documentos',x.id),{status,observacaoAdmin:obs,atualizadoEm:new Date().toISOString(),atualizadoPor:auth.currentUser?.email||''},{merge:true});}
function fechar(){document.querySelector('.access-admin-page')?.remove();}
function pagina(titulo,sub){fechar();const p=document.createElement('section');p.className='access-admin-page';p.innerHTML=`<header><div><span>GESTÃO DE ACESSOS</span><h1>${esc(titulo)}</h1><p>${esc(sub)}</p></div><button data-close>×</button></header><main><div class="access-admin-loading">Carregando...</div></main>`;document.body.appendChild(p);p.querySelector('[data-close]').onclick=fechar;return p;}
async function abrir(tipo='solicitacoes'){
 if(!isAdmin())return alert('Área exclusiva do Admin.');const lista=await acessos();const p=pagina(tipo==='professores'?'Professores':'Solicitações de Acesso',tipo==='professores'?'Gerencie professores autorizados, bloqueados e recusados.':'Analise os primeiros acessos enviados pelos professores.');
 const dados=tipo==='solicitacoes'?lista.filter(x=>x.status==='pendente'):lista;const main=p.querySelector('main');
 main.innerHTML=`<div class="access-admin-toolbar"><button data-tab="solicitacoes" class="${tipo==='solicitacoes'?'active':''}">Pendentes <b>${lista.filter(x=>x.status==='pendente').length}</b></button><button data-tab="professores" class="${tipo==='professores'?'active':''}">Todos os Professores <b>${lista.length}</b></button></div><div class="access-admin-list">${dados.length?dados.map(x=>`<article data-id="${esc(x.id)}"><div class="access-person"><strong>${esc(x.nome||'Professor(a)')}</strong><span>${esc(x.email)}</span><small>Solicitado em ${x.solicitadoEm?new Date(x.solicitadoEm).toLocaleString('pt-BR'):'—'}</small></div><span class="access-badge ${esc(x.status)}">${x.status==='pendente'?'Aguardando aprovação':esc(x.status)}</span><div class="access-actions">${x.status==='pendente'?'<button data-s="ativo" class="approve">Aprovar acesso</button><button data-s="recusado">Recusar</button>':''}${x.status==='ativo'?'<button data-s="bloqueado">Bloquear</button>':''}${x.status==='bloqueado'||x.status==='recusado'?'<button data-s="ativo" class="approve">Reativar / Aprovar</button>':''}</div></article>`).join(''):'<div class="access-empty">Nenhum registro nesta situação.</div>'}</div>`;
 main.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>abrir(b.dataset.tab));main.querySelectorAll('article').forEach(card=>card.querySelectorAll('[data-s]').forEach(b=>b.onclick=async()=>{const x=lista.find(v=>v.id===card.dataset.id);const acao=b.dataset.s;if((acao==='recusado'||acao==='bloqueado')&&!window.confirm(`Confirmar alteração do acesso de ${x.nome||x.email}?`))return;b.disabled=true;await mudar(x,acao);abrir(tipo);}));
}
function instalar(){if(!auth.currentUser||!isAdmin())return;const desktop=document.querySelector('.desktop-header-nav');if(desktop&&!desktop.querySelector('[data-access-admin]')){const b=document.createElement('button');b.type='button';b.dataset.accessAdmin='1';b.innerHTML='👥 Acessos';b.onclick=()=>abrir('solicitacoes');desktop.appendChild(b);}const drawer=document.querySelector('.floating-menu-nav');if(drawer&&!drawer.querySelector('[data-access-admin]')){const g=document.createElement('div');g.className='floating-menu-group access-menu-group';g.innerHTML='<span class="floating-menu-label">ACESSOS</span>';const b=document.createElement('button');b.type='button';b.dataset.accessAdmin='1';b.innerHTML='<span>👥</span> Solicitações de Acesso';b.onclick=()=>{abrir('solicitacoes');document.querySelector('.floating-nav-shell')?.classList.remove('open');};g.appendChild(b);drawer.appendChild(g);}}
if(typeof window!=='undefined'){setInterval(instalar,1000);window.SFDAccessApproval={abrir};}
